# These are populated when your service is created via the ADP Portal scaffolder. Do not change these, as they are abstracted from your service and are mandatory. They are for your reference here.
name: ffc-sfd-ingress
namespace: fcp-sfd
workstream: fcp-sfd

# You may add further labels to identify the service or what your component does.
labels:
  component: web

# Here you can define your Priority classes, min/max replicables etc. Empty block does the HELM Library defaults.
deployment: {}

# These are populated when your service is created via the ADP Portal scaffolder. Do not change these, as they are abstracted from your service and are mandatory. They are for your reference here.
# Your URL will be your <service-name>.<environment>.adp.defra.gov.uk for a front-end Web UI component. Azure Front Door is the Global Load Balancer, CDN and WAF. Nginx is the in-cluster ingress controller.
ingress:
  class: nginx
  endpoint: ffc-sfd
  server: adp.defra.gov.uk
  type: master
  path: /
  defaultPath: /landing-page